[package]
name = "voronoi"
version = "0.1.0"
authors = ["Daniel Maycock <DanMaycock13@googlemail.com>"]
edition = "2018"

[dependencies]
generational-arena = "0.1.0"
rand = "0.6.0"
log = "0.4.6"
piston_window = "0.85.0"

